version: '2'
services:
  db:
    restart: always
    image: postgres:alpine
  redis:
    restart: always
    image: redis:alpine
  web:
    restart: always
    build: .
    env_file: .env.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/mastodon/app
      - ./tmp:/mastodon/tmp
      - ./db:/mastodon/db
      - ./config:/mastodon/config
      - ./public/assets:/mastodon/public/assets
      - ./public/system:/mastodon/public/system
  streaming:
    restart: always
    build: .
    env_file: .env.dev
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  sidekiq:
    restart: always
    build: .
    env_file: .env.dev
    command: bundle exec sidekiq -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system
