FROM nginx:alpine

RUN apk update && apk add certbot

RUN mkdir /root/gcloud-certs-keys
RUN apk add --update \
    python \
    py-pip \
    py-cffi \
    py-cryptography \
    ca-certificates \
  && update-ca-certificates \
  && pip install -U --trusted-host pypi.python.org pip \
  && apk add --virtual build-deps \
    gcc \
    libffi-dev \
    python-dev \
    linux-headers \
    musl-dev \
    openssl-dev \
  && pip install -U --trusted-host pypi.python.org gsutil pyasn1 \
  && apk del build-deps \
  && rm -rf /var/cache/apk/*

RUN mkdir /acme-ssl
RUN mkdir /etc/letsencrypt

COPY public /public
COPY nginx_boto.conf /root/.boto
COPY nginx_entrypoint.sh /root/
COPY nginx_fetch_certs.sh /root/
COPY nginx_put_certs.sh /root/

CMD /root/nginx_entrypoint.sh
